# Explorando matrices y operaciones básicas

El propósito de esta actividad es experimentar con la librería numpy creando y
realizando operaciones básicas sobre matrices.

1. Se importa la librería numpy.

In [2]:
import numpy as np

2. Se crea una matriz de 3 x 3 con números del 1 al 9.

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

3. Se suma 10 a la matriz A

In [3]:
A + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

4. Se multiplica la matriz A por 2.

In [4]:
A * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

5. Se extraen los elementos de la matriz A que son mayores a 5.

In [5]:
A[A > 5]

array([6, 7, 8, 9])

6. Se realiza la asignación B=A y se reemplaza el elemento central de la matriz B por 1. El resultado es que la matriz A también es modificada.
   Esto se debe a que las matrices A y B ocupan el mismo espacio de memoria.

In [6]:
B = A
B[1, 1] = 1
A

array([[1, 2, 3],
       [4, 1, 6],
       [7, 8, 9]])

7. Se realiza la misma operación anterior, pero esta vez con la asignación B=A.copy() y se reemplaza el elemento central de la matriz B por 1. El resultado es que la matriz A ahora no cambia, esto debido a que el método copy transfiere los datos de la matriz A a la matriz B, no solo el espacio de memoria.

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A.copy()
B[1, 1] = 1
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])