# Generación de datos y redimensionado

Esta actividad busca fortalecer el dominio sobre las funciones predefinidas para crear arreglos, generar datos de prueba y reestructurar datos.

1. Se importa la librería numpy

In [1]:
import numpy as np

2. Se crea un arreglo con números del 1 al 16 usando la función arange y se redimensiona a una matriz de 4 x 4 usando el método reshape.

In [2]:
x = np.arange(1, 17)
x = x.reshape(4, 4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

3. Se usa la función linspace para crear un arreglo con 10 elementos equiespaciados entre 0 y 100.

In [5]:
y = np.linspace(0, 100, 10)
y

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

4. Se crea una matriz de 3 x 3 con números aleatorios entre 1 y 20.

In [6]:
z = np.random.randint(1, 20, (3, 3))
z

array([[ 1, 18, 14],
       [ 7, 10, 10],
       [15,  8,  7]], dtype=int32)

5. Se calcula la raíz y el logaritmo de los arreglos.

In [7]:
np.sqrt(y)

array([ 0.        ,  3.33333333,  4.71404521,  5.77350269,  6.66666667,
        7.45355992,  8.16496581,  8.81917104,  9.42809042, 10.        ])

In [8]:
np.log(z)

array([[0.        , 2.89037176, 2.63905733],
       [1.94591015, 2.30258509, 2.30258509],
       [2.7080502 , 2.07944154, 1.94591015]])